language: go

go:
  #- 1.6.x
  #- 1.7.x
  #- 1.8.x
  #- 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

script:
  - go test ./...
 
go_import_path: github.com/ggarau/gox
 
deploy:
  provider: releases
  api_key:
    secure: "<encrypted-token>"
  file: 'gox'
  skip_cleanup: true
  draft: true
#  on:
#    tags
